server:
  port: 80
  servlet:
    context-path: / #项目的上下文路径

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false
    # mybatis plus配置
mybatis-plus:
    mapper-locations: classpath:/mybatis/*.xml #加载映射文件
    type-aliases-package: com.yx.bean #别名搜索的包
    configuration:
      lazy-loading-enabled: true #打开懒加载
      aggressive-lazy-loading: false #关闭积极懒加载
